name: BTCUSDT
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - deprecated=1.2.13
  - filelock=3.17.0
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - fsspec=2024.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libta-lib=0.4.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.5.0
  - opentelemetry-api=1.30.0
  - packaging=24.2
  - pandas=2.2.3
  - pandas-ta=0.3.14b
  - pillow=11.1.0
  - pip=25.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2024.1
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - requests=2.32.3
  - setuptools=78.1.1
  - sip=6.10.0
  - six=1.17.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - ta-lib=0.4.32
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - joblib==1.5.0
      - numpy==2.2.5
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - threadpoolctl==3.6.0
